---
stages:
  - build
  - deploy

# Dummy build job: simply copy files from one directory to another.
build:
  stage: build
  image: ubuntu
  script:
    - cp src/* public/
  artifacts:
    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    paths:
      - public/
    expire_in: 30 days

# Start or re-deploy review application: run `make start` and use
# URL-friendly branch name as the review app "alias".
start_review:
  stage: deploy
  image: python
  before_script:
    - pip install -q awscli
  script:
    - make start ALIAS=$CI_COMMIT_REF_SLUG
  environment:
    name: "development/${CI_COMMIT_REF_SLUG}"
    url: "https://${CI_COMMIT_REF_SLUG}.review.man.wtf/"
    on_stop: stop_review
  except:
    refs:
      - master
      - schedules
      - tags
  dependencies:
    - build

# Stop a review application: run `make stop`.
# This job is automatically executed when a Merge Request is closed.
stop_review:
  stage: deploy
  image: python
  before_script:
    - pip install -q awscli
  script:
    - make stop ALIAS=$CI_COMMIT_REF_SLUG
  environment:
    name: "development/${CI_COMMIT_REF_SLUG}"
    url: "https://${CI_COMMIT_REF_SLUG}.review.man.wtf/"
    action: stop
  when: manual
  except:
    refs:
      - master
      - schedules
      - tags
